### ISSUE TITLE
Remove the thumbnail from the Item Record

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/YouTubeImport#21]
All of the users preferred only including the embedded video in the Item Record display

YouTube Usability Report item 2.3.1.2

**Comment by NedHenry** [comment]
Fixed in 21d34c12223320b0e1741061dc1a71912a6cb611, both for public and admin views. The imported thumbnail file is stored in the metadata element "Imported Thumbnail", to distinguish it from any other files that might be added to the item. Then, javascript hides this element from admin and public views in most standard themes.
